server:
  port: 8009

---
#MariaDB
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cat_shop
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
---

---
#Thymeleaf
spring:
    thymeleaf:
        prefix : classpath:templates/
        suffix : .html
        cache : false
---

#Mybatis
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml

#GITIGNORE TEST